language: ruby
rvm:
  - 2.3.1
  - 1.9.3
env:
  - 'ADAPTER=activerecord'
  - 'ADAPTER=datamapper'
  - 'ADAPTER=mongoid'
before_script:
  - if [[ "$ADAPTER" == "mongoid" ]]; then sudo service mongodb start; fi
branches:
  only:
    - master
